apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yaoyaoji.fullname" . }}-config
  labels:
    {{- include "yaoyaoji.labels" . | nindent 4 }}
data:
  MYSQL_HOST: "{{ include "yaoyaoji.fullname" . }}-mysql"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: {{ .Values.config.database | quote }}
  MYSQL_USER: "root"
  APP_NAME: {{ .Values.config.appName | quote }}
  APP_VERSION: {{ .Values.config.appVersion | quote }}
  ALGORITHM: {{ .Values.config.algorithm | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.config.accessTokenExpireMinutes | quote }}
  DEEPSEEK_BASE_URL: {{ .Values.config.deepseekBaseUrl | quote }}
  DEBUG: {{ .Values.config.debug | quote }}
