apiVersion: v1
kind: Service
metadata:
  name: {{ include "yaoyaoji.fullname" . }}-frontend
  labels:
    {{- include "yaoyaoji.frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontend
    {{- include "yaoyaoji.selectorLabels" . | nindent 4 }}
