{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "yaoyaoji.fullname" . }}-ingress
  labels:
    {{- include "yaoyaoji.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ include "yaoyaoji.fullname" . }}-backend
            port:
              number: 8000
      - path: /uploads
        pathType: Prefix
        backend:
          service:
            name: {{ include "yaoyaoji.fullname" . }}-backend
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "yaoyaoji.fullname" . }}-frontend
            port:
              number: 80
{{- end }}
