apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yaoyaoji.fullname" . }}-secret
  labels:
    {{- include "yaoyaoji.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.secrets.mysqlPassword | b64enc | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | b64enc | quote }}
  DEEPSEEK_API_KEY: {{ .Values.secrets.deepseekApiKey | b64enc | quote }}
